# Generated by Django 4.2.3 on 2023-07-27 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('condition', models.CharField(choices=[('N', 'Like New'), ('S', 'Slightly Damaged'), ('D', 'Damaged')], default='N', max_length=1)),
                ('sonnyangel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.sonny')),
            ],
        ),
    ]
