# Generated by Django 4.2.3 on 2023-07-31 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_outfit_alter_inspect_options_alter_inspect_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sonny',
            name='outfits',
            field=models.ManyToManyField(to='main_app.outfit'),
        ),
    ]
